url: http://localhost:3000/
port: 3000
allowedPrivateNetworks: [
  127.0.0.1/32
]

db:
  host: db
  port: 5432
  db: misskey
  user: misskey-test
  pass: misskey-test
  extra:
    statement_timeout: 60000,

redis:
  host: redis
  port: 6379
